"""Generate bge_m3_lite/_grapheme_data.py from the Unicode Character Database.

Usage: python tools/gen_grapheme_tables.py <dir with GraphemeBreakProperty.txt,
emoji-data.txt, DerivedCoreProperties.txt>
"""

import re
import sys
from pathlib import Path

GCB_VALUES = [
    "Other",
    "CR",
    "LF",
    "Control",
    "Extend",
    "ZWJ",
    "Regional_Indicator",
    "Prepend",
    "SpacingMark",
    "L",
    "V",
    "T",
    "LV",
    "LVT",
]
INCB_VALUES = ["None", "Consonant", "Extend", "Linker"]

LINE = re.compile(
    r"^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*([A-Za-z_]+)\s*(?:;\s*([A-Za-z_]+))?"
)


def parse(path: Path, wanted: str | None = None):
    out = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        m = LINE.match(line)
        if not m:
            continue
        lo, hi, prop, value = m.groups()
        if wanted is not None:
            if prop != wanted:
                continue
            prop = value
        out.append((int(lo, 16), int(hi or lo, 16), prop))
    return out


def merge(ranges, names):
    ranges.sort()
    merged = []
    for lo, hi, val in ranges:
        idx = names.index(val)
        if merged and merged[-1][1] + 1 == lo and merged[-1][2] == idx:
            merged[-1] = (merged[-1][0], hi, idx)
        else:
            merged.append((lo, hi, idx))
    return merged


def main():
    src = Path(sys.argv[1])
    gcb = merge(parse(src / "GraphemeBreakProperty.txt"), GCB_VALUES)
    ext = merge(
        [r for r in parse(src / "emoji-data.txt") if r[2] == "Extended_Pictographic"],
        ["Other", "Extended_Pictographic"],
    )
    incb = merge(parse(src / "DerivedCoreProperties.txt", "InCB"), INCB_VALUES)
    header = src / "GraphemeBreakProperty.txt"
    match = re.search(r"GraphemeBreakProperty-([\d.]+)\.txt", header.read_text())
    if match is None:
        raise SystemExit("cannot find the Unicode version in GraphemeBreakProperty.txt")
    version = match.group(1)
    dest = Path(__file__).resolve().parent.parent / "bge_m3_lite" / "_grapheme_data.py"
    with open(dest, "w", encoding="utf-8") as fh:
        fh.write(
            '"""Unicode grapheme cluster tables. Generated by tools/gen_grapheme_tables.py."""\n\n'
        )
        fh.write(f'UNICODE_VERSION = "{version}"\n\n')
        fh.write(f"GCB_NAMES = {GCB_VALUES!r}\n")
        fh.write(f"INCB_NAMES = {INCB_VALUES!r}\n\n")
        for name, table in (("GCB", gcb), ("EXTPICT", ext), ("INCB", incb)):
            fh.write(f"# {len(table)} ranges: (start, end, value_index)\n")
            fh.write(f"{name}_STARTS = (\n")
            for i in range(0, len(table), 8):
                fh.write(
                    "    " + ", ".join(str(r[0]) for r in table[i : i + 8]) + ",\n"
                )
            fh.write(")\n")
            fh.write(f"{name}_ENDS = (\n")
            for i in range(0, len(table), 8):
                fh.write(
                    "    " + ", ".join(str(r[1]) for r in table[i : i + 8]) + ",\n"
                )
            fh.write(")\n")
            fh.write(f"{name}_VALUES = (\n")
            for i in range(0, len(table), 16):
                fh.write(
                    "    " + ", ".join(str(r[2]) for r in table[i : i + 16]) + ",\n"
                )
            fh.write(")\n\n")
    print(
        f"wrote {dest}: GCB={len(gcb)} ExtPict={len(ext)} InCB={len(incb)} (Unicode {version})"
    )


if __name__ == "__main__":
    main()
